import { Link } from 'react-router-dom';

export default function Privacy() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <Link to="/" className="text-sm text-purple-400 hover:text-purple-300">
          &larr; Back
        </Link>

        <h1 className="text-3xl font-bold text-white mt-4 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-10">Last updated: April 29, 2026</p>

        <div className="space-y-8 text-gray-300 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">The short version</h2>
            <p>
              Film Freaks (&ldquo;Arcy Station&rdquo;) is a movie list tracker. We store the
              data you give us so the app works. We don&rsquo;t run ads, we don&rsquo;t use
              analytics, and we don&rsquo;t sell anything to anyone. If you want your data
              deleted, email us and we&rsquo;ll delete it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Who we are</h2>
            <p>
              This service is operated by Arcturus, an individual operator based in Illinois,
              United States. For any privacy question or request, contact:{' '}
              <a
                href="mailto:kwinklerjs@gmail.com"
                className="text-purple-400 hover:text-purple-300 underline"
              >
                kwinklerjs@gmail.com
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">What we collect</h2>
            <p className="mb-3">When you sign in with Google, we receive and store:</p>
            <ul className="list-disc pl-6 space-y-1 mb-4">
              <li>Your name (as set on your Google account)</li>
              <li>Your email address</li>
              <li>Your Google profile photo URL</li>
              <li>The date your account was created</li>
            </ul>

            <p className="mb-3">As you use the app, we also store the things you create:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Lists you make, including titles, descriptions, and the movies in them</li>
              <li>Which movies you&rsquo;ve marked as watched</li>
              <li>Ratings and review notes you write on movies</li>
              <li>Reactions you leave on friends&rsquo; reviews</li>
              <li>Friend connections, friend requests, and list invitations</li>
              <li>Notifications generated by the above activity</li>
              <li>Personal preferences such as pinned lists</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">What we don&rsquo;t collect</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>We don&rsquo;t use any analytics or tracking SDKs.</li>
              <li>We don&rsquo;t use cookies for advertising.</li>
              <li>We don&rsquo;t fingerprint your device.</li>
              <li>We don&rsquo;t sell or rent your data to anyone, ever.</li>
              <li>We don&rsquo;t serve advertisements.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">How we use your data</h2>
            <p>
              The data above is used solely to operate the app: showing you your lists,
              showing your friends what you&rsquo;ve watched and reviewed, sending notifications,
              and identifying you when you sign back in. That&rsquo;s it. We don&rsquo;t use it
              for marketing, profiling, or training AI models.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Third-party services</h2>
            <p className="mb-3">
              Film Freaks relies on a few third-party services to function. When you use the
              app, some of your data is sent to these providers under their own privacy
              policies:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong className="text-white">Google (Firebase)</strong> &mdash; hosts the app,
                handles sign-in, and stores all of your data. Google sees your IP address and
                technical request metadata in their normal server logs.
              </li>
              <li>
                <strong className="text-white">Google Identity</strong> &mdash; verifies who
                you are when you sign in with Google.
              </li>
              <li>
                <strong className="text-white">The Movie Database (TMDB)</strong> &mdash; your
                browser fetches movie information directly from TMDB. TMDB sees your IP address
                and the searches/movies you look at. We don&rsquo;t send TMDB any account
                information.
              </li>
              <li>
                <strong className="text-white">Wikipedia</strong> &mdash; your browser fetches
                plot summaries directly from Wikipedia. Wikipedia sees your IP address and the
                article titles you look up.
              </li>
            </ul>
            <p className="mt-3">
              This product uses the TMDB API but is not endorsed or certified by TMDB.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Public sharing</h2>
            <p>
              If you create a public share link for a list, anyone with that link can see the
              list&rsquo;s title, description, and the movies in it. Public share pages do
              <strong> not </strong>
              expose your name, ratings, reviews, friends, or any other personal information.
              You can stop sharing at any time by toggling sharing off on the list.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Local storage on your device</h2>
            <p>
              The app stores a small amount of non-personal data in your browser&rsquo;s
              storage to make the app faster: a cache of popular movies (refreshed weekly), a
              cached &ldquo;pick of the week,&rdquo; and temporary state like scroll position
              and filter selections. None of this is sent anywhere; clearing your browser data
              clears it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Who can see your data</h2>
            <p>
              Other signed-in users see information about you according to the in-app rules:
              friends can see your watched movies, ratings, and reviews; non-friends generally
              cannot. The operator of Film Freaks (the developer behind the app) has technical
              administrative access to the database and is therefore able to read user data.
              This access is used only to keep the service running, investigate bugs, and
              respond to abuse reports &mdash; not to browse user content for fun.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Your choices and rights</h2>
            <p className="mb-3">You can:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                <strong className="text-white">See your data</strong> &mdash; almost everything
                we have about you is visible to you in the app. For anything else, email us.
              </li>
              <li>
                <strong className="text-white">Correct your data</strong> &mdash; edit lists,
                reviews, and your displayed name/photo through Google.
              </li>
              <li>
                <strong className="text-white">Delete your data</strong> &mdash; email{' '}
                <a
                  href="mailto:kwinklerjs@gmail.com"
                  className="text-purple-400 hover:text-purple-300 underline"
                >
                  kwinklerjs@gmail.com
                </a>{' '}
                from the address on your account. We&rsquo;ll delete your profile, your lists,
                your reviews, your friend connections, and your notifications within 30 days.
                Cached movie information from TMDB and Wikipedia is not personal and is kept.
                An in-app self-service deletion flow is on the way.
              </li>
              <li>
                <strong className="text-white">Stop using the app</strong> &mdash; you can sign
                out at any time. Signing out doesn&rsquo;t delete your data; emailing us does.
              </li>
            </ul>
            <p className="mt-3">
              If you&rsquo;re in a jurisdiction with additional rights (for example, the
              EU/EEA, UK, or California), you have those rights too. Just email us.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Children</h2>
            <p>
              Film Freaks is not intended for children under 13. We don&rsquo;t knowingly
              collect personal information from anyone under 13. If you believe a child under
              13 has created an account, email us and we&rsquo;ll delete it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Security</h2>
            <p>
              Your data is stored in Google Firebase, which encrypts data at rest and in
              transit. Sign-in is handled by Google. No system is perfectly secure; if we ever
              learn of a breach affecting your account, we&rsquo;ll notify you by email.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Changes to this policy</h2>
            <p>
              If this policy changes in a meaningful way, we&rsquo;ll update the &ldquo;Last
              updated&rdquo; date above and, for material changes, notify signed-in users
              inside the app. Continued use after a change means you accept the updated policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Contact</h2>
            <p>
              Questions, requests, complaints, or concerns:{' '}
              <a
                href="mailto:kwinklerjs@gmail.com"
                className="text-purple-400 hover:text-purple-300 underline"
              >
                kwinklerjs@gmail.com
              </a>
              .
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
